# Generated by Django 2.2.1 on 2019-06-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do item')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Codigo')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Quantidade')),
                ('description', models.TextField(blank=True, verbose_name='Descriçao do item')),
                ('price_of_sale', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço de venda')),
                ('price_of_buy', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Preço de compra')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('category', models.CharField(choices=[('S', 'Serviço'), ('P', 'Produto')], max_length=8, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['name'],
            },
        ),
    ]
