# Generated by Django 2.2.1 on 2020-04-17 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_of_buy',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Preço de compra'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_of_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Preço de venda'),
        ),
    ]
