# Generated by Django 2.2.1 on 2019-06-16 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('telephone', models.CharField(max_length=12, null=True, verbose_name='Telefone')),
                ('rua', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('bairro', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cidade')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complemento')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('species', models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato'), ('A', 'Ave'), ('R', 'Roedor'), ('P', 'Peixe'), ('R', 'Reptil'), ('Os', 'Outros')], max_length=20, null=True, verbose_name='Espécie')),
                ('breed', models.CharField(blank=True, max_length=30, null=True, verbose_name='Raça')),
                ('gender', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho'), ('I', 'Indefinido')], max_length=8, verbose_name='Gênero')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['owner', 'name'],
            },
        ),
    ]
